Add thomson to nstx machine mappings
gafusion/omas pull request #210
Opened 2022-09-07 06:51 UTC by jmcclena

2022-09-07 16:07 UTC, orso82 requested changes
looks good. Only few minor changes

2022-09-07 16:07 UTC, orso82 commented on omas/machine_mappings/nstxu.py
> +    Gathers DIII-D Thomson measurement locations
DIII-D --> NSTX(-U) here and elsewhere
```suggestion
    Gathers NSTX(-U) Thomson measurement locations
```

2022-09-07 16:07 UTC, orso82 commented on omas/machine_mappings/nstxu.py
> +
you can format the OMAS source by typing `make format` at the top-level folder

2022-09-07 16:07 UTC, orso82 commented on omas/machine_mappings/nstxu.py
> +    print(res)
cruft

2022-09-13 17:29 UTC, smithsp commented
@jmcclena has addressed changes.  Requested review by @orso82  again.

2022-09-19 19:10 UTC, orso82 commented
@jmcclena if you find it useful, these are the updated ECH mappings as I did them https://github.com/gafusion/omas/tree/ech_imasv37

2022-09-19 19:13 UTC, orso82 commented
@jmcclena let me know when/if you want to merge

2022-09-20 17:29 UTC, smithsp commented
https://github.com/gafusion/omas/compare/jmcclena_nstx_thomson...ech_imasv37 may be useful

2022-10-04 16:57 UTC, merged